In [69]:
import os
import pandas as pd
from matplotlib import pyplot

In [70]:
rcsv = pd.read_csv('busidx.csv')

In [71]:
rcsv.tail()

,Indx,Series reference,Period,Description,Revised,Initially published
62,K173,2019.12,PPIQ.SQUCC1300,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
63,K174,2019.09,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1243,1241
64,K175,2019.12,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
65,K176,2019.12,PPIQ.SQUCC3200,"Pulp, Paper and Converted Paper Product, Outpu...",1015,1014
66,K177,2019.12,PPIQ.SQUCC3210,"Pulp, Paper and Converted Paper Product Manufa...",1015,1014

In [8]:
rcsv.shape

(67, 5)

In [9]:
rcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Series reference     67 non-null     float64
 1   Period               67 non-null     object
 2   Description          67 non-null     object
 3   Revised              67 non-null     int64
 4   Initially published  67 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 2.7+ KB

In [20]:
pd.set_option('display.max_columns', 10)

In [40]:
rcsv[2:5]

,Series reference,Period,Description,Revised,Initially published
2,2019.09,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1167,1164
3,2019.12,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1170,1166
4,2019.09,PPIQ.SQN900000,"All industries, Inputs Indexes (Level 0)",1166,1164

In [41]:
rcsv

,Series reference,Period,Description,Revised,Initially published
0,2019.09,PPIQ.SQN800000,"All industries excl admin health educati, Inpu...",1167,1164
1,2019.12,PPIQ.SQN800000,"All industries excl admin health educati, Inpu...",1170,1166
2,2019.09,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1167,1164
3,2019.12,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1170,1166
4,2019.09,PPIQ.SQN900000,"All industries, Inputs Indexes (Level 0)",1166,1164
...,...,...,...,...,...
62,2019.12,PPIQ.SQUCC1300,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
63,2019.09,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1243,1241
64,2019.12,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
65,2019.12,PPIQ.SQUCC3200,"Pulp, Paper and Converted Paper Product, Outpu...",1015,1014
66,2019.12,PPIQ.SQUCC3210,"Pulp, Paper and Converted Paper Product Manufa...",1015,1014

In [43]:
rcsv.iloc[[62, 63], 1]

62    PPIQ.SQUCC1300
63    PPIQ.SQUCC1310
Name: Period, dtype: object

In [46]:
rcsv.loc[[34, 38], 'Period']

34    PPIQ.SQUAA1000
38    PPIQ.SQUAA1110
Name: Period, dtype: object

In [47]:
rcsv.columns

Index(['Series reference', 'Period', 'Description', 'Revised',
       'Initially published'],
      dtype='object')

In [49]:
rcsv.index

RangeIndex(start=0, stop=67, step=1)

In [58]:
rcsv

,Series reference,Period,Revised,Initially published
Description,,,,
"All industries excl admin health educati, Inputs Indexes (Level 0)",2019.09,PPIQ.SQN800000,1167,1164
"All industries excl admin health educati, Inputs Indexes (Level 0)",2019.12,PPIQ.SQN800000,1170,1166
"All industries ex admin health edu OOD, Inputs Indexes (Level 0)",2019.09,PPIQ.SQN800001,1167,1164
"All industries ex admin health edu OOD, Inputs Indexes (Level 0)",2019.12,PPIQ.SQN800001,1170,1166
"All industries, Inputs Indexes (Level 0)",2019.09,PPIQ.SQN900000,1166,1164
...,...,...,...,...
"Dairy Product Manufacturing, Outputs Indexes (Level 3)",2019.12,PPIQ.SQUCC1300,1220,1217
"Dairy Product Manufacturing, Outputs Indexes (Level 4)",2019.09,PPIQ.SQUCC1310,1243,1241
"Dairy Product Manufacturing, Outputs Indexes (Level 4)",2019.12,PPIQ.SQUCC1310,1220,1217
"Pulp, Paper and Converted Paper Product, Outputs Indexes (Level 3)",2019.12,PPIQ.SQUCC3200,1015,1014
"Pulp, Paper and Converted Paper Product Manufactur, Outputs Indexes (Level 4)",2019.12,PPIQ.SQUCC3210,1015,1014

In [64]:
rcsv.set_index(inplace=True)

TypeError: set_index() missing 1 required positional argument: 'keys'

In [63]:
rcsv

,Series reference,Period,Revised,Initially published
Description,,,,
"All industries excl admin health educati, Inputs Indexes (Level 0)",2019.09,PPIQ.SQN800000,1167,1164
"All industries excl admin health educati, Inputs Indexes (Level 0)",2019.12,PPIQ.SQN800000,1170,1166
"All industries ex admin health edu OOD, Inputs Indexes (Level 0)",2019.09,PPIQ.SQN800001,1167,1164
"All industries ex admin health edu OOD, Inputs Indexes (Level 0)",2019.12,PPIQ.SQN800001,1170,1166
"All industries, Inputs Indexes (Level 0)",2019.09,PPIQ.SQN900000,1166,1164
...,...,...,...,...
"Dairy Product Manufacturing, Outputs Indexes (Level 3)",2019.12,PPIQ.SQUCC1300,1220,1217
"Dairy Product Manufacturing, Outputs Indexes (Level 4)",2019.09,PPIQ.SQUCC1310,1243,1241
"Dairy Product Manufacturing, Outputs Indexes (Level 4)",2019.12,PPIQ.SQUCC1310,1220,1217
"Pulp, Paper and Converted Paper Product, Outputs Indexes (Level 3)",2019.12,PPIQ.SQUCC3200,1015,1014
"Pulp, Paper and Converted Paper Product Manufactur, Outputs Indexes (Level 4)",2019.12,PPIQ.SQUCC3210,1015,1014

In [65]:
rcsv.reset_index(inplace=True)

In [73]:
rcsv.set_index('Indx', inplace=True)

In [81]:
rcsv

,Series reference,Period,Description,Revised,Initially published
Indx,,,,,
K111,2019.09,PPIQ.SQN800000,"All industries excl admin health educati, Inpu...",1167,1164
K112,2019.12,PPIQ.SQN800000,"All industries excl admin health educati, Inpu...",1170,1166
K113,2019.09,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1167,1164
K114,2019.12,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1170,1166
K115,2019.09,PPIQ.SQN900000,"All industries, Inputs Indexes (Level 0)",1166,1164
...,...,...,...,...,...
K173,2019.12,PPIQ.SQUCC1300,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
K174,2019.09,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1243,1241
K175,2019.12,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
K176,2019.12,PPIQ.SQUCC3200,"Pulp, Paper and Converted Paper Product, Outpu...",1015,1014
K177,2019.12,PPIQ.SQUCC3210,"Pulp, Paper and Converted Paper Product Manufa...",1015,1014

In [90]:
rcsv.loc['K113', 'Description']

'All industries ex admin health edu OOD, Inputs Indexes (Level 0)'

In [94]:
rcsv.loc['K177']

Series reference                                                 2019.12
Period                                                    PPIQ.SQUCC3210
Description            Pulp, Paper and Converted Paper Product Manufa...
Revised                                                             1015
Initially published                                                 1014
Name: K177, dtype: object

In [104]:
pd.set_option('display.max_columns', 10)
rcsv

,Series reference,Period,Description,Revised,Initially published
Indx,,,,,
K111,2019.09,PPIQ.SQN800000,"All industries excl admin health educati, Inpu...",1167,1164
K112,2019.12,PPIQ.SQN800000,"All industries excl admin health educati, Inpu...",1170,1166
K113,2019.09,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1167,1164
K114,2019.12,PPIQ.SQN800001,"All industries ex admin health edu OOD, Inputs...",1170,1166
K115,2019.09,PPIQ.SQN900000,"All industries, Inputs Indexes (Level 0)",1166,1164
...,...,...,...,...,...
K173,2019.12,PPIQ.SQUCC1300,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
K174,2019.09,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1243,1241
K175,2019.12,PPIQ.SQUCC1310,"Dairy Product Manufacturing, Outputs Indexes (...",1220,1217
K176,2019.12,PPIQ.SQUCC3200,"Pulp, Paper and Converted Paper Product, Outpu...",1015,1014
K177,2019.12,PPIQ.SQUCC3210,"Pulp, Paper and Converted Paper Product Manufa...",1015,1014

In [105]:
dff = pd.DataFrame(rcsv)

In [108]:
dff.columns

Index(['Series reference', 'Period', 'Description', 'Revised',
       'Initially published'],
      dtype='object')

In [116]:
flt1 = rcsv['Revised'] == 1220

In [117]:
rcsv[flt1].iloc[0:2, 2:3]

                                            Description
Indx
K173  Dairy Product Manufacturing, Outputs Indexes (...
K175  Dairy Product Manufacturing, Outputs Indexes (...